spring.application.name=StockManager

spring.jpa.defer-datasource-initialization=true

# Data Source MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/(YOUR DATABASE)?useSSL=true&serverTimezone=UTC
spring.datasource.username=(YOUR USERNAME)
spring.datasource.password=(YOUR PASSWORD)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
#Mostra no console os logs que o hibernate faz (apenas para desenvolvimento)
spring.jpa.show-sql=true

#servidor
spring.web.error.whitelabel.enabled=false
server.servlet.context-path=/
